homeworks/2024/041w.txt
=> 041w_homework1

homeworks/2024/006m.txt
there is the homework including a link about my repository called 006m which is the same name as this txt.
=> 1st_homework_by_006m

homeworks/2024/yaoUoE
This is the first homework from yao.
=> 1st Homework

homeworks/2024/011a
My first homework, my name is aolu.
=> first homework_al

homeworks/2024/012z
=> first commit_zhl

homeworks/2024/013z
=> First assignment

homeworks/2024/025J
=> jiangfangfirstwork

homeworks/2024/058z
=> Add 058z.txt

homeworks/2024/038s.txt
=> first homework

homeworks/2024/012X, homeworks/2024/012x.txt
=> 1st homework commit

homeworks/2025/044HJM, homeworks/2025/044HJM.txt
=> hjm‘s homework

homeworks/2025/006H.txt
=> 006HYT提交作业

homeworks/2025/011WJM.txt
This pull request adds the file 011WJM.txt to the homeworks-2025 folder. The file includes the correct links to my GitHub repositories created in Task 1 and Task 2. This is a resubmission after the previous issue where files were mistakenly deleted.
from 242302011 Wang Jiamo
=> Re-submit 011WJM.txt with correct repository links

homeworks/2025/001ZXF.txt
=> Added homework file 001ZXF.txt

R4Psy.Rproj, homeworks/2025/online_BB_0308.txt
=> Online_homework

homeworks/2025/044HTY.txt
=> 044HTY Homework1

homeworks/2025/016JWB.txt
=> Add homework file 016JWB.txt

homeworks/2025/027ZY.txt
=> added a text

homeworks/2025/023JCH, homeworks/2025/023JCH.txt
=> 023JCH'task

homeworks/2025/060QZY.txt
=> add my first task

homeworks/2025/online_Vvvl_0311
=> Add homework_Vvvl

chapter6_practice_new.Rmd, chapter6_practice_new.html
=> chapter6_practice_new

homeworks/2025/online_LXY_0412
assign homework1 to Homework/2025
=> online_LXY_0412 assign homework1

homeworks/2025/064WSY_homework2.Rmd
=> add homework2

homeworks/2025/019YZH_hw2.Rmd
This is 019YZH's second homework. Thanks!
=> 019YZH's second homework

homeworks/2025/008NJM_homework2.Rmd
=> 008NJM_homework2

homeworks/2025/044HTY_homework2.Rmd
=> 044HTY_homework2

homeworks/2025/030QRQ_homework 2.Rmd
=> 030QRQ_homework 2

homeworks/2025/002RWJ_hw2.Rmd
=> homework2_5.29

homeworks/2025/005CQY_hw2.Rmd
=> 005CQY_hw2_2nd

chapter_14.qmd, homeworks/2025/054ZHS_homework2.Rmd
=> 054ZHS_homework2

homeworks/2025/031DMJ_2nd_homework.Rmd
031DMJ_2nd_homework.Rmd
Thanks！
=> 031DMJ_2nd_homework.Rmd

homeworks/2025/034-BYR-homework2.Rmd
=> 034-BYR-homework2
